name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Install Node dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Rsync to server
        uses: contention/rsync-deployments@v2.0.0
        with:
          flags: -avzr --delete
          excludes: |
            .env
            storage
            node_modules
            .git
            cypress
            tests
            .specs
          localpath: ./
          remotepath: /var/www/fin/
          host: 167.235.153.124
          user: gustavo
          deploy_key: ${{ secrets.SSH_KEY }}
      # Manter comentado por enquanto
      # - name: Deploy containers
      #   uses: appleboy/ssh-action@v1
      #   with:
      #     host: 167.235.153.124
      #     username: gustavo
      #     key: ${{ secrets.SSH_KEY }}
      #     script: cd /var/www/fin && ./scripts/deploy.sh
